# This is a basic workflow to help you get started with Actions

- name: Create Issue Branch
  # You may pin to the exact commit or the version.
  # uses: robvanderleek/create-issue-branch@83e252424396af292511477235958adb34bb6423
  uses: robvanderleek/create-issue-branch@v1.5
  
on:
    issues:
        types: [assigned]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
